### ISSUE TITLE
Response Unauthorized

### ISSUE THREAD

**Issue by baaronp7** [ghaiklor/passport-twitch-token#94]
Hello,

I put in my client id and client secret but when I go to "localhost:3000/auth/twitch" I get back "Unauthorized" any ideas?

**Comment by baaronp7** [comment]
Here is my code btw:

var TwitchTokenStrategy = require('passport-twitch-token');
var TWITCH_CLIENT_ID = "------------------------------------";
var TWITCH_CLIENT_SECRET = "----------------------------------";

passport.use(new TwitchTokenStrategy({
    clientID: TWITCH_CLIENT_ID,
    clientSecret: TWITCH_CLIENT_SECRET,
    passReqToCallback: true
}, function(req, accessToken, refreshToken, profile, next) {
    User.findOrCreate({'twitch.id': profile.id}, function(error, user) {
        return next(error, user);
    });
}));

app.get('/auth/twitch', passport.authenticate('twitch-token'));

**Comment by ghaiklor** [comment]
@baaronp7 I don't see the code where you passing access token to `/auth/twitch/`.

**Comment by baaronp7** [comment]
I thought that '/auth/twitch' returned the auth token. If not where do I get the access token from?

**Comment by ghaiklor** [comment]
@baaronp7 quote from a readme:

> Passport strategy for authenticating with Twitch access tokens using the OAuth 2.0 API.

You must to obtain an access token and then provide it to this library. You can get access token in many ways, follow the guides from their documentation.

**Comment by siltwood** [comment]
Where do we provide it to this library?

**Comment by MuteBard** [comment]
I apologize for reviving this thread but I'm not too sure of where to provide the token to in this library

**Comment by ghaiklor** [comment]
Guys, seriously, do you even read documentation? https://github.com/ghaiklor/passport-twitch-token#authenticate-requests

<img width="866" alt="Screen Shot 2020-06-06 at 10 26 20" src="https://user-images.githubusercontent.com/3625244/83938805-3744f380-a7e0-11ea-9a79-5db097bc1e05.png">
